// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("athena_metrics_encoding")
	ScopeName = "github.com/shuttle-hq/athenametricsencodingextension"
)

const (
	ExtensionStability = component.StabilityLevelAlpha
)
